name: Deploy Website ke Server

on:
  push:
    branches:
      - main  # Pastikan nama branch utama Anda 'main' atau 'master'

jobs:
  web-deploy:
    name: ðŸŽ‰ Deploy ke Hosting
    runs-on: ubuntu-latest
    steps:
    - name: ðŸšš Get latest code
      uses: actions/checkout@v4

    - name: ðŸ“‚ Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}

        # Pastikan folder tujuan sudah benar (sesuai settingan cPanel Anda)
        server-dir: /public_html/kursus.quizb.my.id/

        exclude: |
          **/.git*
          **/.github*
          **/README.md
          **/*.sql
